### ISSUE TITLE
filters not working

### ISSUE THREAD

**Issue by iiiiii1wepfj** [SpEcHiDe/PyroGramBot#32]
2020-11-22 22:29:33,761 - pyrogram.dispatcher - ERROR - '-id'
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pyrogram/dispatcher.py", line 208, in handler_worker
    await handler.callback(self.client, *args)
  File "/root/PyroGramBot/pyrobot/plugins/tlifers/save.py", line 98, in save_filter
    client.filterstore[str(chat_id)][filter_kw] = fm_id
KeyError: '-id'

**Comment by Dank-del** [comment]
Yea same here, can't save filters, its forwarding the stuff to the db chat but not saving the filter
